#!/bin/bash
jindu(){
TIME=0.1
COUNT="0"
while :
do
COUNT=`expr $COUNT + 1`
case $COUNT in
"1")
  echo  -e '-'"\b\c"
  sleep $TIME
  ;;
"2")
  echo -e  '\\'"\b\c"
  sleep $TIME
  ;;
"3")
  echo -e  "|\b\c"
  sleep $TIME
  ;;
"4")
  echo -e "/\b\c"
  sleep $TIME
  ;;
*)
  COUNT="0";;
 esac
done
}
jindu
